### ISSUE TITLE
Menu App Crashes

### ISSUE THREAD

**Issue by CaspervdGeer** [rsyncOSX/RsyncOSXsched#304] opened 2020-07-16 08:28 UTC
Hi Thomas, 

The menu app is not working on my computer. It worked fine the first time I launched it but not since then. I updated to the latest version a couple of days but the problem is the same.

1. Menu app loads when computer starts (icon is visible in menu bar)
2. When I click on the icon, it just disappears
3. RsyncOSX works fine and tasks are executed properly
4. I can launch the menu app from within RsyncOSX and the icon appears on the menu bar but it disappears when I click on it
5. When I delete the task I have made in RsyncOSX, the menu app works fine!
6. The task I have made is a simple synchronise of a local folder to an external hard drive.

Your help would be much appreciated,
Casper

**Comment by rsyncOSX** [comment] 2020-07-18 14:07
Hi, sorry for not responding to this issue before now... It is difficult to diagnose why this happens.

There might be some problems with the config files? I can help to diagnose what happens if you can drop me the content of the Documents/Rsync catalog..  There are no secret info in the config files, it is safe drop the catalog here...

**Comment by rsyncOSX** [comment] 2020-07-18 14:17
As a test I just started from scratch (moved Documents/Rsync catalog to a backup location).. Started with an empty config, added a task and then added a daily schedule .. all works
<img width="1204" alt="Skjermbilde 2020-07-18 kl  16 13 28" src="https://user-images.githubusercontent.com/22427340/87854416-22e13400-c912-11ea-9a96-f6cb435e534b.png">
<img width="1204" alt="Skjermbilde 2020-07-18 kl  16 13 34" src="https://user-images.githubusercontent.com/22427340/87854418-25dc2480-c912-11ea-980e-23e4bbc5b9ac.png">
<img width="759" alt="Skjermbilde 2020-07-18 kl  16 14 07" src="https://user-images.githubusercontent.com/22427340/87854421-283e7e80-c912-11ea-872d-9fcfff41358e.png">

 as expected..

**Comment by CaspervdGeer** [comment] 2020-07-18 15:49
Hi, thanks for getting back to me about this issue.
As per your test, I also have no problem setting up a new task and it will run fine the first time.
After that, however, it does not work anymore and the menu app crashes.

I have attached the config and schedule files here in the ZIP file.

[Archive.zip](https://github.com/rsyncOSX/RsyncOSXsched/files/4941935/Archive.zip)

**Comment by rsyncOSX** [comment] 2020-07-18 15:52
Hi..

I will test it right away :-)

lør. 18. jul. 2020 kl. 17:49 skrev CaspervdGeer <notifications@github.com>:

**Comment by rsyncOSX** [comment] 2020-07-18 16:01
There is something odd with the config file (schedule file), it makes the schedule part crash.. I will investigate what happens during, probably later this evening or tomorrow morning...
<img width="1440" alt="Skjermbilde 2020-07-18 kl  17 57 56" src="https://user-images.githubusercontent.com/22427340/87856644-ad309480-c920-11ea-92fe-4bdbf073338c.png">

**Comment by CaspervdGeer** [comment] 2020-07-18 16:12
Okay, many thanks.
There is no rush!

FYI, I have deleted the task that was in the previous schedule that I sent you.
I made two new scheduled tasks and one of them just executed perfectly.
The files are attached here, maybe it can help you.

[ArchiveNEW.zip](https://github.com/rsyncOSX/RsyncOSXsched/files/4941959/ArchiveNEW.zip)

**Comment by rsyncOSX** [comment] 2020-07-18 16:14
Well, a quick fix is : delete the `scheduleRsync.plist` and start over..  I managed to create a schedule and the menu app picks it up.. Will also look into your recent file as well :-)
<img width="1204" alt="Skjermbilde 2020-07-18 kl  18 10 13" src="https://user-images.githubusercontent.com/22427340/87856874-52983800-c922-11ea-8a60-87c6294dba20.png">
<img width="759" alt="Skjermbilde 2020-07-18 kl  18 10 54" src="https://user-images.githubusercontent.com/22427340/87856877-54fa9200-c922-11ea-8a06-fbce13a5fca8.png">

**Comment by rsyncOSX** [comment] 2020-07-18 17:56
I did find what caused the error. There was, by some reason, an error within the `scheduleRsync.plist` file.. it is an XML-file and one element was not terminated.. So, the remedy is delete the `scheduleRsync.plist` file and make another daily schedule :-) I will make the loading of files more secure....

<img width="1157" alt="Skjermbilde 2020-07-18 kl  19 49 52" src="https://user-images.githubusercontent.com/22427340/87858757-8e39fe80-c930-11ea-853f-5100e3e58457.png">

**Comment by rsyncOSX** [comment] 2020-07-19 06:26
> I did find what caused the error. There was, by some reason, an error within the `scheduleRsync.plist` file.. it is an XML-file and one element was not terminated.. So, the remedy is delete the `scheduleRsync.plist` file and make another daily schedule :-) I will make the loading of files more secure....

Well, the above was not true - there was something else causing it.. I did find where it happens, but I dont understand exactly why.. The remedy is to delete the `scheduleRsync.plist` and start over again.. I am closing the issue, hopefully this will work for you...

**Closed by rsyncOSX** 2020-07-19 06:26 UTC

**Comment by CaspervdGeer** [comment] 2020-07-20 09:11
Hi Thomas, 

I have tried your suggestion again today and also did this on Saturday (delete plist files and make new tasks and schedule). The menu app is displaying the same behaviour (disappears/crashes when I click on it).

It seems to go wrong after the first scheduled task has run.

I can send you the new plist files if you want.

Thanks,
Casper

**Comment by rsyncOSX** [comment] 2020-07-20 18:26
Hi..

Send me the .plist files again, I will check it again tomorrow..
I have been busy today..

Regards..
Thomas

man. 20. jul. 2020 kl. 11:11 skrev CaspervdGeer <notifications@github.com>:

**Comment by CaspervdGeer** [comment] 2020-07-21 08:46
I have attached the new plist files here. 

Thanks again,
Casper

[Archive.zip](https://github.com/rsyncOSX/RsyncOSXsched/files/4952297/Archive.zip)

**Comment by rsyncOSX** [comment] 2020-07-21 12:11
I will check the files later this evening..
By the way, there is a new release candidate, can you try they as well..

Regards,
Thomas

tir. 21. jul. 2020 kl. 10:46 skrev CaspervdGeer <notifications@github.com>:

**Comment by rsyncOSX** [comment] 2020-07-21 18:50
Hi, I do see where it crashes but I dont know what happens.. You might try this yourself in a editor.. I am running the latest release candidates (from today) and both RsyncOSX and the menu app crashes opening your original files. If you delete the `scheduleRsync.plist` (which keeps the logs and schedules) - RsyncOSX does execute.. 

Here is what your `scheduleRsync.plist` looks like:

<img width="912" alt="original" src="https://user-images.githubusercontent.com/22427340/88093471-55995f80-cb92-11ea-88bb-29a65cab7ba4.png">

I did the following change (in a editor) and everything works as expected.. Download the latest release candidate, copy the changed archive.zip files (attached) and see what happen..
[Arkiv.zip](https://github.com/rsyncOSX/RsyncOSXsched/files/4955552/Arkiv.zip)
 After coping files, try to add another weekly schedule with start like tomorrow and see what happens...

<img width="912" alt="changed" src="https://user-images.githubusercontent.com/22427340/88093535-6e097a00-cb92-11ea-85b4-cce203b241b3.png">

This is what it look like after change...

<img width="759" alt="Skjermbilde 2020-07-21 kl  20 45 09" src="https://user-images.githubusercontent.com/22427340/88094108-4b2b9580-cb93-11ea-916e-bda29c4ffc80.png">

 <img width="1204" alt="Skjermbilde 2020-07-21 kl  20 44 53" src="https://user-images.githubusercontent.com/22427340/88094100-4961d200-cb93-11ea-8e51-3e94ac488d7e.png">

**Comment by rsyncOSX** [comment] 2020-07-21 21:38
Hi..

There is some issues with the menu app related to your problems. Thx for your input I have removed a couple of lines of code and built new release candidates. I will investigate what is happening, removed lines of code is not critical... 

Please download the updated release candidates.. And thx for reporting the issue...

**Comment by rsyncOSX** [comment] 2020-07-21 22:11
For your info, there is still an issue - dont know what happens, but with new release candidates the menu app does not crash. Loading your .plist files within the menu app does not show an active schedule.. dont know why, but if you add a new schedule it should work. I am not able to produce the same error my self, but I have your files to work on...

**Comment by rsyncOSX** [comment] 2020-07-22 19:47
Hi..

The issue you reported was very real and a hard on to crack, there was an issue with dates and leapyear which I did not see, until now.. There are still some minor issues to solve, but your problem is solved.. A new release candidate will come in some days, please use RsyncOSX only.. Sorry about the Norwegian in views, but this is your plist files..

Thx for reporting the issue..

<img width="1204" alt="Skjermbilde 2020-07-22 kl  21 33 50" src="https://user-images.githubusercontent.com/22427340/88221444-cd37bf00-cc64-11ea-92e2-e684ddc757d7.png">
<img width="759" alt="Skjermbilde 2020-07-22 kl  21 34 09" src="https://user-images.githubusercontent.com/22427340/88221465-d4f76380-cc64-11ea-96d7-5e2d228e96a9.png">

**Comment by rsyncOSX** [comment] 2020-07-23 07:23
The issue is now solved, new release candidate is uploaded.

**Comment by CaspervdGeer** [comment] 2020-07-23 09:26
Thank you very much for taking the time to work on the issue. I will download and install the latest release now.

**Comment by rsyncOSX** [comment] 2020-07-23 16:10
I have updated the [changelog](https://rsyncosx.netlify.app/post/changelog/). The bug was critical and thank your very much for reporting it. This is how open source apps becomes better, bugs are reported :-)
